---
- hosts: $hosts
  user: $user
  sudo: yes
  vars:
    app_name: Trim\ Enabler
    app_name_pretty: Trim Enabler
    app_url: http://groths.org/trimenabler/TrimEnabler.dmg
    installer_type: app
    install_method: dmg
    mount_path: /Volumes/Trim\ Enabler/
  vars_files:
    - ../setup-vars.yaml
  tasks:
    - include: ../setup.yaml
    - include: ../install/$install_method.yaml