---
- hosts: $hosts
  user: $user
  sudo: yes
  vars:
    app_name: AppCleaner
    app_name_pretty: AppCleaner
    app_url: http://www.freemacsoft.net/downloads/AppCleaner_2.1.zip
    installer_type: app
    install_method: zip
  vars_files:
    - ../setup-vars.yaml
  tasks:
    - include: ../setup.yaml
    - include: ../install/$install_method.yaml