---
- hosts: $hosts
  user: $user
  vars:
    app_name: Coda
    app_name_pretty: Coda
    app_url: https://panic.com/coda/d/Coda%202.0.7.zip
    installer_type: app
    install_method: zip
  vars_files:
    - ../setup-vars.yaml
  tasks:
    - include: ../setup.yaml
    - include: ../install/$install_method.yaml