---
- hosts: $hosts
  user: $user
  sudo: yes
  vars:
    app_name: Keka
    app_name_pretty: Keka
    app_url: http://download.kekaosx.com/
    installer_type: app
    install_method: dmg
    mount_path: /Volumes/Keka/
  vars_files:
    - ../setup-vars.yaml
  tasks:
    - include: ../setup.yaml
    - include: ../install/$install_method.yaml