---
- hosts: $hosts
  user: $user
  sudo: yes
  vars:
    app_name: VLC
    app_name_pretty: VLC
    app_url: https://copy.com/8WKZ3x1ZWOIC/VLC-2.0.6.dmg?download=1
    installer_type: app
    install_method: dmg
    mount_path: /Volumes/vlc-2.0.6/
  vars_files:
    - ../setup-vars.yaml
  tasks:
    - include: ../setup.yaml
    - include: ../install/$install_method.yaml