---
- hosts: $hosts
  user: $user
  sudo: yes
  vars:
    app_name: Brackets\ Sprint\ 23
    app_name_pretty: Brackets
    app_url: http://download.brackets.io/file.cfm?platform=OSX&build=23
    installer_type: app
    install_method: dmg
    mount_path: /Volumes/Brackets\ Sprint\ 23/
  vars_files:
    - ../setup-vars.yaml
  tasks:
    - include: ../setup.yaml
    - include: ../install/$install_method.yaml