---
- hosts: $hosts
  user: $user
  vars:
    app_name: Mou
    app_name_pretty: Mou
    app_url: http://mouapp.com/download/Mou.zip
    installer_type: app
    install_method: zip
  vars_files:
    - ../setup-vars.yaml
  tasks:
    - include: ../setup.yaml
    - include: ../install/$install_method.yaml