---
- hosts: $hosts
  user: $user
  vars:
    app_name: CodeKit
    app_name_pretty: CodeKit
    app_url: http://incident57.com/codekit/files/codekit-8283.zip
    installer_type: app
    install_method: zip
  vars_files:
    - ../setup-vars.yaml
  tasks:
    - include: ../setup.yaml
    - include: ../install/$install_method.yaml