---
- hosts: $hosts
  user: $user
  sudo: yes
  vars:
    app_name: Texts
    app_name_pretty: Texts
    app_url: http://www.texts.io/Texts-0.13.1.dmg
    installer_type: app
    install_method: dmg
    mount_path: /Volumes/Texts/
  vars_files:
    - ../setup-vars.yaml
  tasks:
    - include: ../setup.yaml
    - include: ../install/$install_method.yaml