---
- hosts: $hosts
  user: $user
  sudo: yes
  vars:
    app_name: Alfred\ 2
    app_name_pretty: Alfred
    app_url: http://cachefly.alfredapp.com/Alfred_2.0.3_187.zip
    installer_type: app
    install_method: zip
  vars_files:
    - ../setup-vars.yaml
  tasks:
    - include: ../setup.yaml
    - include: ../install/$install_method.yaml