---
- hosts: $hosts
  user: $user
  vars:
    app_name: Sequel\ Pro
    app_name_pretty: Sequel Pro
    app_url: http://sequel-pro.googlecode.com/files/sequel-pro-1.0.1.dmg
    installer_type: app
    install_method: dmg
    mount_path: /Volumes/Sequel\ Pro\ 1.0.1/
  vars_files:
    - ../setup-vars.yaml
  tasks:
    - include: ../setup.yaml
    - include: ../install/$install_method.yaml