---
- hosts: $hosts
  user: $user
  vars:
    app_name: Slicy
    app_name_pretty: Slicy
    app_url: http://macrabbit.com/slicy/get/
    installer_type: app
    install_method: zip
  vars_files:
    - ../setup-vars.yaml
  tasks:
    - include: ../setup.yaml
    - include: ../install/$install_method.yaml