---
- hosts: $hosts
  user: $user
  sudo: yes
  vars:
    app_name: Opera
    app_name_pretty: Opera
    app_url: http://ftp.opera.com/pub/opera/mac/1215/Opera_12.15_Setup_Intel.dmg
    installer_type: app
    install_method: dmg
    mount_path: /Volumes/Opera/
  vars_files:
    - ../setup-vars.yaml
  tasks:
    - include: ../setup.yaml
    - include: ../install/$install_method.yaml