---
- hosts: $hosts
  user: $user
  sudo: yes
  vars:
    app_name: LimeChat
    app_name_pretty: LimeChat
    app_url: https://downloads.sourceforge.net/project/limechat/limechat/LimeChat_2.34.tbz?use_mirror=master
    installer_type: app
    install_method: tar
  vars_files:
    - ../setup-vars.yaml
  tasks:
    - include: ../setup.yaml
    - include: ../install/$install_method.yaml