---
- hosts: $hosts
  user: $user
  sudo: yes
  vars:
    app_name: Transmit
    app_name_pretty: Transmit
    app_url: http://www.panic.com/transmit/d/Transmit%204.3.3.zip
    installer_type: app
    install_method: zip
  vars_files:
    - ../setup-vars.yaml
  tasks:
    - include: ../setup.yaml
    - include: ../install/$install_method.yaml