---
- hosts: $hosts
  user: $user
  sudo: yes
  vars:
    app_name: Google\ Chrome
    app_name_pretty: Google Chrome
    app_url: https://dl.google.com/chrome/mac/stable/GGRO/googlechrome.dmg
    installer_type: app
    install_method: dmg
    mount_path: /Volumes/Google\ Chrome/
  vars_files:
    - ../setup-vars.yaml
  tasks:
   - include: ../setup.yaml
   - include: ../install/$install_method.yaml