---
- hosts: $hosts
  user: $user
  sudo: yes
  vars:
    app_name: Espresso
    app_name_pretty: Espresso
    app_url: http://macrabbit.com/espresso/get/
    installer_type: app
    install_method: zip
  vars_files:
    - ../setup-vars.yaml
  tasks:
   - include: ../setup.yaml
   - include: ../install/$install_method.yaml