---
- hosts: $hosts
  user: $user
  sudo: yes
  vars:
    app_name: Transmission
    app_name_pretty: Transmission
    app_url: https://copy.com/jTqaA0JWmTmn/Transmission-2.77.dmg?download=1
    installer_type: app
    install_method: dmg
    mount_path: /Volumes/Transmission/
  vars_files:
    - ../setup-vars.yaml
  tasks:
    - include: ../setup.yaml
    - include: ../install/$install_method.yaml