---
- include: ../setup.yaml

- hosts: $hosts
  user: $user
  vars:
    app_name: tree
    app_name_pretty: tree
    install_method: homebrew
  vars_files:
    - ../setup-vars.yaml
  tasks:
    - include: ../install/$install_method.yaml